### ISSUE TITLE
ember cli proxy port 3000

### ISSUE THREAD

**Issue by feitian124** [danlynn/ember-cli-docker-template#1]
hi, i'm running ember-cli project with below config in `.ember-cli`:

``` js
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

    Setting `disableAnalytics` to true will prevent any data from being sent.
  */
  "disableAnalytics": false,
  "proxy": "http://127.0.0.1:3000"
}
```

if run in docker, how should i config to proxy request from port 4200 to 3000?

and port 3000 is  currently used by a rails  project which run in vagrant, so i can not simple export it in `docker-compose.yml`.

any idea? thanks.

**Comment by danlynn** [comment]
You can tweak the docker-compose.yml so that it uses a different port when exposed to the container host than what port it uses to expose to other containers.

The ports config uses a format like <expose_to_host>:<expose_to_containers>.  Thus, by default it is exposing port 4200 to both.

  ports:
    - "4200:4200"
    - "35729:35729"

This is for connections that are connecting to ember server.  

It sounds like you have another web server running somewhere.  If it is on your host machine and not in a container then you should be able to connect directly to it from within the container by using the VM's IPNAT host gateway address generically (192.168.99.1 for virtualbox), (192.168.156.1 for vmwarefusion).  Or you might be able to point it at your actual host machine's DNS name on your local network.  I'd use the generic VM IPNAT addresses though so it is more generic and not tied to your specific host name.

If the web server is running in another container then be sure to expose its ports in the normal docker-compose.yml way.

Good luck!
